apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chainr-work.fullname" . }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "watch", "delete"]
