name: chainr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    - name: Check go formatting
      run: make check-fmt

    - name: Run unit tests
      run: make test
