name: chainr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    - name: Install dependencies
      run: make deps

    - name: Check formatting
      run: make check-fmt

    - name: Run unit tests
      run: make test

    - name: Build docker images
      run: make docker-build

    - name: Login to Dockerhub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - name: Push docker images
      run: make docker-push
